# Generated by Django 5.0 on 2024-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аббревиатура'),
        ),
    ]
