# Generated by Django 5.0 on 2024-09-15 19:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=500, verbose_name='Название кафедры')),
                ('title_short', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Cathedra',
                'verbose_name_plural': 'Cathedras',
                'db_table': 'univer_cathedra',
            },
        ),
    ]
