# Generated by Django 5.0 on 2024-09-15 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_cathedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathedra',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cathedra', to='structure.institute', verbose_name='Институт'),
        ),
    ]
