# Generated by Django 5.0.7 on 2024-07-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_employeeprofile_user_alter_studentprofile_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeeprofile",
            options={"verbose_name": "employee", "verbose_name_plural": "employees"},
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={"verbose_name": "student", "verbose_name_plural": "students"},
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Мужчина"), ("F", "Женщина")],
                default="M",
                max_length=8,
                verbose_name="Пол",
            ),
            preserve_default=False,
        ),
    ]
