# Generated by Django 5.0.7 on 2024-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_employeeprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужчина"), ("F", "Женщина")],
                max_length=8,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
