# Generated by Django 5.0.7 on 2024-07-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_employeeprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужчина"), ("F", "Женщина")],
                max_length=8,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
