# Generated by Django 5.0.7 on 2024-07-26 12:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_employeeprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128,
                null=True,
                region=None,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Отчество"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
