# Generated by Django 5.0.7 on 2024-07-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_studentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
