<<<<<<< HEAD
# Generated by Django 5.0 on 2024-09-11 12:22
=======
# Generated by Django 5.0 on 2024-08-24 06:51
>>>>>>> a2e425315993913f4194d5c756daad3f3b667074

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_alter_univerbranch_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='univerbranch',
            options={'verbose_name': 'Univer branch', 'verbose_name_plural': 'Univer branches'},
        ),
    ]
